config/routes.rb
Rails.application.routes.draw do
  get 'targets/index'

  root 'targets#index'

  resources :targets do
    collection do
      get 'import'
      post 'import'
    end
  end

end

app/models/anm_report_annual_target.rb
class AnmReportAnnualTarget < ActiveRecord::Base
  self.table_name = "anm_report.annual_target"

  belongs_to :dim_anm, :foreign_key => 'anmidentifier'
  belongs_to :dim_indicator, :foreign_key => 'indicator'

  validates_presence_of :dim_anm, :dim_indicator, :target, :start_date, :end_date

  def self.import(anm_identifier, indicator, target, start_date, end_date)
    anm_report_annual_target = fetch(anm_identifier, indicator, start_date, end_date)
    if(anm_report_annual_target.nil?)
      anm_report_annual_target = AnmReportAnnualTarget.new(:start_date => start_date, :end_date => end_date)
      anm_report_annual_target.dim_anm = DimAnm.where(:anmidentifier => anm_identifier).first
      anm_report_annual_target.dim_indicator = DimIndicator.where(:indicator => indicator).first
    end
    anm_report_annual_target.target = target
    anm_report_annual_target.valid? ? anm_report_annual_target.save! : false
  end

  def self.fetch(anm_identifier, indicator, start_date, end_date)
    AnmReportAnnualTarget.where(
        :dim_anm => DimAnm.where(:anmidentifier => anm_identifier),
        :dim_indicator => DimIndicator.where(:indicator => indicator),
        :start_date => start_date,
        :end_date => end_date).first
  end
end

app/models/anm_report_annual_target_sp.rb
class AnmReportAnnualTargetSp < ActiveRecord::Base
  self.table_name = "report.annual_target"

  belongs_to :dim_service_provider, :foreign_key => 'service_provider'
  belongs_to :dim_indicator_sp, :foreign_key => 'indicator'

  validates_presence_of :dim_service_provider, :dim_indicator_sp, :target, :start_date, :end_date

  def self.import(anm_identifier, indicator, target, start_date, end_date)
    anm_report_annual_target_sp = fetch(anm_identifier, indicator, start_date, end_date)
    if(anm_report_annual_target_sp.nil?)
      anm_report_annual_target_sp = AnmReportAnnualTargetSp.new(:start_date => start_date, :end_date => end_date)
      anm_report_annual_target_sp.dim_service_provider = DimServiceProvider.where(:dim_anm_sp => DimAnmSp.where(:anmidentifier => anm_identifier)).first
      anm_report_annual_target_sp.dim_indicator_sp = DimIndicatorSp.where(:indicator => indicator).first
    end
    anm_report_annual_target_sp.target = target
    if(anm_report_annual_target_sp.valid?)
      anm_report_annual_target_sp.save!
    end
  end

  def self.fetch(anm_identifier, indicator, start_date, end_date)
    AnmReportAnnualTargetSp.where(
        :dim_service_provider => DimServiceProvider.where(:dim_anm_sp => DimAnmSp.where(:anmidentifier => anm_identifier)),
        :indicator => DimIndicatorSp.where(:indicator => indicator),
        :start_date => start_date,
        :end_date => end_date).first
  end
end

app/models/dim_anm.rb
class DimAnm < ActiveRecord::Base
  self.table_name = "anm_report.dim_anm"
end

app/models/dim_anm_sp.rb
class DimAnmSp < ActiveRecord::Base
  self.table_name = "report.dim_anm"
end

app/models/dim_indicator.rb
class DimIndicator < ActiveRecord::Base
  self.table_name = "anm_report.dim_indicator"
end

app/models/dim_indicator_sp.rb
class DimIndicatorSp < ActiveRecord::Base
  self.table_name = "report.dim_indicator"
end

app/models/dim_service_provider.rb
class DimServiceProvider < ActiveRecord::Base
  self.table_name = "report.dim_service_provider"
  self.inheritance_column = nil

  belongs_to :dim_anm_sp, :foreign_key => 'service_provider'
  belongs_to :dim_service_provider_type, :foreign_key => 'type'

  validates_presence_of :dim_anm_sp, :dim_service_provider_type

end

app/models/dim_service_provider_type.rb
class DimServiceProviderType < ActiveRecord::Base
  self.table_name = "report.dim_service_provider_type"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/targets_controller.rb
require 'anm_report_annual_target'
require 'anm_report_annual_target_sp'

class TargetsController < ApplicationController
  def index
  end

  def import
    file = params[:file]
    @count = 0
    @error_records = []
    importFile(file)
  end

  def importFile(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]

      anm_identifier, end_date, indicator, start_date, target = sanitise(row)

      if ([anm_identifier, indicator, target, start_date, end_date].include?(nil))
        add_error_record(anm_identifier, indicator, target, start_date, end_date)
        next
      end

      unless AnmReportAnnualTarget.import(anm_identifier, indicator, target, start_date, end_date)
        add_error_record(anm_identifier, indicator, target, start_date, end_date)
        next
      end

      unless AnmReportAnnualTargetSp.import(anm_identifier, indicator, target, start_date, end_date)
        add_error_record(anm_identifier, indicator, target, start_date, end_date)
        next
      end
    end
  end

  def open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then
        Roo::Csv.new(file.path, nil, :ignore)
      when ".xls" then
        Roo::Excel.new(file.path)
      when ".xlsx" then
        Roo::Excelx.new(file.path)
      else
        raise "Unknown file type: #{file.original_filename}"
    end
  end

  def sanitise(row)
    anm_identifier = row["ANM Identifier"]
    anm_identifier = anm_identifier.nil? ? nil : anm_identifier.strip

    indicator = row["Indicator"]
    indicator = indicator.nil? ? nil : indicator.strip

    target = row["Target"]
    target = target.nil? ? nil : row["Target"].to_int.to_s.strip

    start_date = row["start_date"]
    start_date = start_date.nil? ? nil : start_date

    end_date = row["end_date"]
    end_date = end_date.nil? ? nil : end_date
    return anm_identifier, end_date, indicator, start_date, target
  end

  def add_error_record(anm_identifier, indicator, target, start_date, end_date)
    error_record = Hash.new
    error_record[:indicator] = indicator
    error_record[:target] = target
    error_record[:start_date] = start_date
    error_record[:end_date] = end_date
    error_record[:anm_identifier] = anm_identifier
    @error_records.append(error_record)
    @count = @count + 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DristhiAnnualTargets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/targets/import.html.erb
<% if @count == 0 %>
    <h1>Imported Successfully</h1>
<% else %>
    <h1><%=@count%> record(s) failed import</h1>
<% end %>

<% unless @count == 0 %>
    <table>
      <tr>
        <th>AnmIdentifier</th>
        <th>Indicator</th>
        <th>Target</th>
        <th>StartDate</th>
        <th>EndDate</th>
      </tr>
      <% @error_records.each do |error_record| %>
          <tr>
            <td><%= error_record[:anm_identifier] %></td>
            <td><%= error_record[:indicator] %></td>
            <td><%= error_record[:target] %></td>
            <td><%= error_record[:start_date] %></td>
            <td><%= error_record[:end_date] %></td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/targets/index.html.erb
<h2>Import Rules</h2>
<p>The excel file columns and values should follow the below rules:</p>
<p>1) There should be a column with name 'ANM Identifier' and the corresponding values should be non-empty string</p>
<p>2) There should be a column with name 'Indicator' and the corresponding values should be non-empty string</p>
<p>3) There should be a column with name 'Target' and the corresponding values should be non-empty integer > 0</p>
<p>4) There should be a column with name 'start_date' and the corresponding values should be YYYY-MM-DD formated date </p>
<p>5) There should be a column with name 'end_date' and the corresponding values should be YYYY-MM-DD formated date </p>

<h2>Import Annual Targets</h2>

<%= form_tag import_targets_path, multipart:true do %>
<%= file_field_tag :file %>
<%= submit_tag "Import" %>
<% end %>

</br>